
import { ForestRegion, IncidentType, Language, IncidentReport, RegionType } from './types';

export const BIH_CENTER: [number, number] = [44.1, 17.9];

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: 'Forest Guard',
    map: 'Map',
    reports: 'Reports',
    stats: 'Statistics',
    layers: 'Layers',
    reportIncident: 'Report Incident',
    system: 'System',
    support: 'Support',
    fireAlert: 'Fire Alert',
    floodAlert: 'Flood Alert',
    description: 'Description',
    location: 'Location',
    submit: 'Submit Report',
    activeOperators: 'Active Operators',
    recentReports: 'Recent Reports',
    systemCoreData: 'System Core Data',
    activeLanguage: 'Active Language',
    surveillanceNetwork: 'Surveillance Network',
    status: 'Status',
    nominal: 'Nominal',
    tracking: 'Tracking',
    alerts: 'Alerts',
    theme: 'Theme',
    liveWindVector: 'Live Wind Vector',
    heatIndex: 'Heat Index',
    forestTemp: 'Forest Temp (Live)',
    assetsRegions: 'Assets & Regions',
    dataOverlays: 'Data Overlays',
    systemConfig: 'System Config',
    gisLegend: 'GIS Legend',
    imagerySource: 'Imagery Source',
    vector: 'Vector',
    forestInventory: 'Forest Inventory',
    activeLandfills: 'Active Landfills',
    protectedAreas: 'Protected Areas',
    fireThreats: 'Fire Threats',
    hydrological: 'Hydrological',
    classLegend: 'Classification Legend',
    regionTypes: {
      [RegionType.DECIDUOUS]: 'Deciduous Forests',
      [RegionType.CONIFEROUS]: 'Coniferous Forests',
      [RegionType.MIXED]: 'Mixed Forests',
      [RegionType.MAQUIS]: 'Maquis',
      [RegionType.LOW_VEGETATION]: 'Low Vegetation',
      [RegionType.LANDFILL]: 'Anthropogenic Landfill'
    },
    popup: {
      dataSync: 'Data Sync',
      surfaceArea: 'Surface Area',
      live: 'Live',
      threatIndex: 'Threat Index'
    },
    legend: {
      activeFire: 'Active Fire',
      activeFlood: 'Active Flood',
      sensorStation: 'Sensor Station',
      liveData: 'Live Data'
    },
    forests: {
      'Kozara National Park': 'Kozara National Park',
      'Sutjeska National Park': 'Sutjeska National Park',
      'Bjelašnica Forest': 'Bjelašnica Forest',
      'Uborak Landfill': 'Uborak Landfill',
      'Jahorina Conifers': 'Jahorina Conifers',
      'Igman Mixed Reserve': 'Igman Mixed Reserve',
      'Vlašić Highland': 'Vlašić Highland',
      'Grmeč Old Growth': 'Grmeč Old Growth',
      'Romanija Pines': 'Romanija Pines',
      'Konjuh Protected': 'Konjuh Protected',
      'Čvrsnica Scrub': 'Čvrsnica Scrub',
      'Majevica Deciduous': 'Majevica Deciduous',
      'Smiljevići Waste Dept': 'Smiljevići Waste Dept',
      'Kurevo Landfill': 'Kurevo Landfill',
      'Desetine Landfill': 'Desetine Landfill',
      'Prenj Alpine Zone': 'Prenj Alpine Zone'
    },
    dashboard: {
      area: 'Area',
      coordinates: 'Coordinates',
      fullData: 'FULL SYSTEM DATA',
      currentConditions: 'Current Conditions',
      feelsLike: 'Feels like',
      wind: 'Wind',
      humidity: 'Humidity',
      pressure: 'Pressure',
      precipitation: 'Precipitation',
      uvIndex: 'UV Index',
      windGusts: 'Wind Gusts',
      forecast24h: '24-Hour Forecast',
      forecast7d: '7-Day Forecast',
      hourlyBtn: 'HOURLY',
      dailyBtn: '7-DAY',
      rainProb: 'Precipitation Probability (12 Hours)',
      fireRisk: 'Fire Risk Analysis (Live)',
      angstrom: 'Angström Index',
      gfi: 'GFI (Forest Fire)',
      kbdi: 'KBDI (Drought)',
      advancedAtmosphere: 'Advanced Atmosphere',
      seaLevelPress: 'Sea Level Press.',
      surfacePress: 'Surface Press.',
      visibility: 'Visibility',
      evapotranspiration: 'Evapotranspiration',
      et0: 'ET₀ (Reference)',
      vapourPress: 'Vapour Press. Def.',
      cloudCover: 'Total Cloud Cover',
      lowClouds: 'Low Clouds',
      midClouds: 'Mid Clouds',
      highClouds: 'High Clouds',
      verticalWind: 'Vertical Wind',
      soilProfile: 'Soil Profile',
      loading: 'Acquiring Telemetry...',
      today: 'Today',
      now: 'Now'
    },
    riskLevels: {
      low: 'Low',
      moderate: 'Moderate',
      high: 'High',
      veryHigh: 'Very High',
      extreme: 'EXTREME'
    },
    weather: {
      0: 'Clear Sky', 1: 'Mainly Clear', 2: 'Partly Cloudy', 3: 'Overcast',
      45: 'Fog', 48: 'Depositing Rime Fog',
      51: 'Light Drizzle', 53: 'Moderate Drizzle', 55: 'Dense Drizzle',
      56: 'Light Freezing Drizzle', 57: 'Dense Freezing Drizzle',
      61: 'Slight Rain', 63: 'Moderate Rain', 65: 'Heavy Rain',
      66: 'Light Freezing Rain', 67: 'Heavy Freezing Rain',
      71: 'Slight Snow', 73: 'Moderate Snow', 75: 'Heavy Snow', 77: 'Snow Grains',
      80: 'Slight Rain Showers', 81: 'Moderate Rain Showers', 82: 'Violent Rain Showers',
      85: 'Slight Snow Showers', 86: 'Heavy Snow Showers',
      95: 'Thunderstorm', 96: 'Thunderstorm with Hail', 99: 'Heavy Thunderstorm with Hail'
    }
  },
  [Language.BS]: {
    appName: 'Šumska Straža',
    map: 'Mapa',
    reports: 'Izvještaji',
    stats: 'Statistika',
    layers: 'Slojevi',
    reportIncident: 'Prijavi Incident',
    system: 'Sistem',
    support: 'Podrška',
    fireAlert: 'Požar',
    floodAlert: 'Poplava',
    description: 'Opis',
    location: 'Lokacija',
    submit: 'Pošalji Izvještaj',
    activeOperators: 'Aktivni Operateri',
    recentReports: 'Nedavni Izvještaji',
    systemCoreData: 'Sistemski Podaci',
    activeLanguage: 'Jezik',
    surveillanceNetwork: 'Mreža Nadzora',
    status: 'Status',
    nominal: 'Nominalan',
    tracking: 'Praćenje',
    alerts: 'Upozorenja',
    theme: 'Tema',
    liveWindVector: 'Vjetar Uživo',
    heatIndex: 'Toplotni Indeks',
    forestTemp: 'Temp. Šume (Uživo)',
    assetsRegions: 'Resursi i Regije',
    dataOverlays: 'Slojevi Podataka',
    systemConfig: 'Konfiguracija',
    gisLegend: 'GIS Legenda',
    imagerySource: 'Izvor Slika',
    vector: 'Vektor',
    forestInventory: 'Inventar Šuma',
    activeLandfills: 'Aktivne Deponije',
    protectedAreas: 'Zaštićena Područja',
    fireThreats: 'Opasnost od Požara',
    hydrological: 'Hidrologija',
    classLegend: 'Legenda Klasifikacije',
    regionTypes: {
      [RegionType.DECIDUOUS]: 'Listopadne Šume',
      [RegionType.CONIFEROUS]: 'Četinarske Šume',
      [RegionType.MIXED]: 'Mješovite Šume',
      [RegionType.MAQUIS]: 'Makija',
      [RegionType.LOW_VEGETATION]: 'Niska Vegetacija',
      [RegionType.LANDFILL]: 'Deponija'
    },
    popup: {
      dataSync: 'Sinhronizacija',
      surfaceArea: 'Površina',
      live: 'Uživo',
      threatIndex: 'Indeks Prijetnje'
    },
    legend: {
      activeFire: 'Aktivan Požar',
      activeFlood: 'Aktivna Poplava',
      sensorStation: 'Senzorska Stanica',
      liveData: 'Podaci Uživo'
    },
    forests: {
      'Kozara National Park': 'Nacionalni Park Kozara',
      'Sutjeska National Park': 'Nacionalni Park Sutjeska',
      'Bjelašnica Forest': 'Šuma Bjelašnica',
      'Uborak Landfill': 'Deponija Uborak',
      'Jahorina Conifers': 'Četinari Jahorina',
      'Igman Mixed Reserve': 'Rezervat Igman',
      'Vlašić Highland': 'Visoravan Vlašić',
      'Grmeč Old Growth': 'Prašuma Grmeč',
      'Romanija Pines': 'Borovi Romanije',
      'Konjuh Protected': 'Zaštićeni Konjuh',
      'Čvrsnica Scrub': 'Makija Čvrsnica',
      'Majevica Deciduous': 'Listopadna Majevica',
      'Smiljevići Waste Dept': 'Deponija Smiljevići',
      'Kurevo Landfill': 'Deponija Kurevo',
      'Desetine Landfill': 'Deponija Desetine',
      'Prenj Alpine Zone': 'Prenj Alpska Zona'
    },
    dashboard: {
      area: 'Površina',
      coordinates: 'Koordinate',
      fullData: 'DETALJNI PODACI',
      currentConditions: 'Trenutni Uslovi',
      feelsLike: 'Osjećaj',
      wind: 'Vjetar',
      humidity: 'Vlažnost',
      pressure: 'Pritisak',
      precipitation: 'Padavine',
      uvIndex: 'UV Indeks',
      windGusts: 'Udari Vjetra',
      forecast24h: 'Prognoza 24h',
      forecast7d: 'Prognoza 7 dana',
      hourlyBtn: 'PO SATIMA',
      dailyBtn: '7 DANA',
      rainProb: 'Vjerovatnoća Padavina (12h)',
      fireRisk: 'Analiza Rizika od Požara',
      angstrom: 'Angström Indeks',
      gfi: 'GFI (Šumski Požar)',
      kbdi: 'KBDI (Suša)',
      advancedAtmosphere: 'Napredna Atmosfera',
      seaLevelPress: 'Pritisak (Nivo Mora)',
      surfacePress: 'Pritisak (Površina)',
      visibility: 'Vidljivost',
      evapotranspiration: 'Evapotranspiracija',
      et0: 'ET₀ (Referentna)',
      vapourPress: 'Deficit Parnog Pritiska',
      cloudCover: 'Oblačnost',
      lowClouds: 'Niski Oblaci',
      midClouds: 'Srednji Oblaci',
      highClouds: 'Visoki Oblaci',
      verticalWind: 'Vertikalni Vjetar',
      soilProfile: 'Profil Tla',
      loading: 'Učitavanje Telemetrije...',
      today: 'Danas',
      now: 'Sada'
    },
    riskLevels: {
      low: 'NIZAK',
      moderate: 'UMJEREN',
      high: 'VISOK',
      veryHigh: 'VRLO VISOK',
      extreme: 'EKSTREMAN'
    },
    weather: {
      0: 'Vedro', 1: 'Pretežno Vedro', 2: 'Djelimično Oblačno', 3: 'Oblačno',
      45: 'Magla', 48: 'Inje',
      51: 'Slaba Rosulja', 53: 'Umjerena Rosulja', 55: 'Gusta Rosulja',
      56: 'Slaba Ledena Rosulja', 57: 'Gusta Ledena Rosulja',
      61: 'Slaba Kiša', 63: 'Umjerena Kiša', 65: 'Jaka Kiša',
      66: 'Slaba Ledena Kiša', 67: 'Jaka Ledena Kiša',
      71: 'Slab Snijeg', 73: 'Umjeren Snijeg', 75: 'Jak Snijeg', 77: 'Snježna Zrna',
      80: 'Slabi Pljuskovi Kiše', 81: 'Umjereni Pljuskovi Kiše', 82: 'Jaki Pljuskovi Kiše',
      85: 'Slabi Pljuskovi Snijega', 86: 'Jaki Pljuskovi Snijega',
      95: 'Grmljavina', 96: 'Grmljavina sa Gradom', 99: 'Jaka Grmljavina sa Gradom'
    }
  },
  [Language.JA]: {
    appName: 'Forest Guard',
    map: '地図',
    reports: 'レポート',
    stats: '統計',
    layers: 'レイヤー',
    reportIncident: '事件を報告',
    system: 'システム',
    support: 'サポート',
    fireAlert: '火災警報',
    floodAlert: '洪水警報',
    description: '説明',
    location: '場所',
    submit: '送信',
    activeOperators: 'アクティブなオペレーター',
    recentReports: '最近のレポート',
    systemCoreData: 'システムコアデータ',
    activeLanguage: '言語',
    surveillanceNetwork: '監視ネットワーク',
    status: 'ステータス',
    nominal: '正常',
    tracking: '追跡中',
    alerts: 'アラート',
    theme: 'テーマ',
    liveWindVector: '風向ベクトル',
    heatIndex: '暑さ指数',
    forestTemp: '森林温度 (ライブ)',
    assetsRegions: '資産と地域',
    dataOverlays: 'データオーバーレイ',
    systemConfig: 'システム設定',
    gisLegend: 'GIS凡例',
    imagerySource: '画像ソース',
    vector: 'ベクトル',
    forestInventory: '森林インベントリ',
    activeLandfills: '埋立地',
    protectedAreas: '保護地域',
    fireThreats: '火災の脅威',
    hydrological: '水文学',
    classLegend: '分類凡例',
    regionTypes: {
      [RegionType.DECIDUOUS]: '落葉樹林',
      [RegionType.CONIFEROUS]: '針葉樹林',
      [RegionType.MIXED]: '混交林',
      [RegionType.MAQUIS]: 'マキー',
      [RegionType.LOW_VEGETATION]: '低植生',
      [RegionType.LANDFILL]: '埋立地'
    },
    popup: {
      dataSync: 'データ同期',
      surfaceArea: '表面積',
      live: 'ライブ',
      threatIndex: '脅威指数'
    },
    legend: {
      activeFire: '火災',
      activeFlood: '洪水',
      sensorStation: 'センサー局',
      liveData: 'ライブデータ'
    },
    forests: {
      'Kozara National Park': 'コザラ国立公園',
      'Sutjeska National Park': 'スティエスカ国立公園',
      'Bjelašnica Forest': 'ビェラシュニツァの森',
      'Uborak Landfill': 'ウボラク埋立地',
      'Jahorina Conifers': 'ヤホリナ針葉樹',
      'Igman Mixed Reserve': 'イグマン混合保護区',
      'Vlašić Highland': 'ヴラシッチ高原',
      'Grmeč Old Growth': 'グルメチ原生林',
      'Romanija Pines': 'ロマニヤ松林',
      'Konjuh Protected': 'コニュ保護区',
      'Čvrsnica Scrub': 'チュヴルスニツァ低木帯',
      'Majevica Deciduous': 'マイェヴィツァ落葉樹',
      'Smiljevići Waste Dept': 'スミリェヴィチ廃棄物',
      'Kurevo Landfill': 'クレヴォ埋立地',
      'Desetine Landfill': 'デセティネ埋立地',
      'Prenj Alpine Zone': 'プレニ高山帯'
    },
    dashboard: {
      area: '面積',
      coordinates: '座標',
      fullData: '詳細データ',
      currentConditions: '現在の状況',
      feelsLike: '体感温度',
      wind: '風',
      humidity: '湿度',
      pressure: '気圧',
      precipitation: '降水量',
      uvIndex: 'UV指数',
      windGusts: '突風',
      forecast24h: '24時間予報',
      forecast7d: '7日間予報',
      hourlyBtn: '毎時',
      dailyBtn: '7日間',
      rainProb: '降水確率 (12時間)',
      fireRisk: '火災リスク分析',
      angstrom: 'オングストローム指数',
      gfi: 'GFI (森林火災)',
      kbdi: 'KBDI (干ばつ)',
      advancedAtmosphere: '高度な大気データ',
      seaLevelPress: '海面気圧',
      surfacePress: '地上気圧',
      visibility: '視程',
      evapotranspiration: '蒸発散量',
      et0: 'ET₀ (基準)',
      vapourPress: '蒸気圧差',
      cloudCover: '雲量',
      lowClouds: '下層雲',
      midClouds: '中層雲',
      highClouds: '上層雲',
      verticalWind: '垂直風',
      soilProfile: '土壌プロファイル',
      loading: 'テレメトリ取得中...',
      today: '今日',
      now: '現在'
    },
    riskLevels: {
      low: '低',
      moderate: '中',
      high: '高',
      veryHigh: '非常に高い',
      extreme: '危険'
    },
    weather: {
      0: '快晴', 1: '概ね晴れ', 2: '一部曇り', 3: '曇り',
      45: '霧', 48: '着氷性の霧',
      51: '弱い霧雨', 53: '並の霧雨', 55: '強い霧雨',
      56: '弱い着氷性の霧雨', 57: '強い着氷性の霧雨',
      61: '小雨', 63: '並の雨', 65: '大雨',
      66: '弱い着氷性の雨', 67: '強い着氷性の雨',
      71: '小雪', 73: '並の雪', 75: '大雪', 77: '霧雪',
      80: '弱い雨', 81: '並の雨', 82: '激しい雨',
      85: '弱い雪', 86: '激しい雪',
      95: '雷雨', 96: '雹を伴う雷雨', 99: '激しい雹を伴う雷雨'
    }
  }
};

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-001',
    type: IncidentType.FIRE,
    lat: 43.8563,
    lng: 18.4131,
    description: 'Smoke reported near Trebević peak, strong wind carrying it north.',
    timestamp: Date.now() - 3600000,
    urgency: 'high',
    windDirection: 180,
    windSpeed: 25
  },
  {
    id: 'inc-002',
    type: IncidentType.FLOOD,
    lat: 44.7722,
    lng: 17.1910,
    description: 'River Vrbas overflowing near Banja Luka center.',
    timestamp: Date.now() - 7200000,
    urgency: 'medium'
  }
];

export const MOCK_FORESTS: ForestRegion[] = [
  // Major Landfills (Deponije)
  { id: 'dep-1', name: 'Deponija Uborak (Mostar)', type: RegionType.LANDFILL, area: 150, riskScore: 0.95, coordinates: [43.4132, 17.8887] },
  { id: 'dep-2', name: 'Deponija Smiljevići (Sarajevo)', type: RegionType.LANDFILL, area: 210, riskScore: 0.88, coordinates: [43.8864, 18.3600] },
  { id: 'dep-3', name: 'Deponija Ramići (Banja Luka)', type: RegionType.LANDFILL, area: 180, riskScore: 0.82, coordinates: [44.8572, 17.1565] },
  { id: 'dep-4', name: 'Deponija Desetine (Tuzla)', type: RegionType.LANDFILL, area: 120, riskScore: 0.91, coordinates: [44.5375, 18.6258] },
  { id: 'dep-5', name: 'Deponija Mošćanica (Zenica)', type: RegionType.LANDFILL, area: 140, riskScore: 0.75, coordinates: [44.1755, 17.9610] },
  { id: 'dep-6', name: 'Deponija Eko-Dep (Bijeljina)', type: RegionType.LANDFILL, area: 130, riskScore: 0.70, coordinates: [44.7877, 19.1837] },

  // Forests and Regions
  { id: '1', name: 'Sutjeska National Park', type: RegionType.MIXED, area: 17500, riskScore: 0.2, coordinates: [43.3444, 18.6833] },
  { id: '2', name: 'Kozara National Park', type: RegionType.DECIDUOUS, area: 3375, riskScore: 0.45, coordinates: [45.0083, 16.8914] },
  { id: '3', name: 'Mount Igman', type: RegionType.CONIFEROUS, area: 5400, riskScore: 0.8, coordinates: [43.75, 18.25] },
  { id: '4', name: 'Una National Park', type: RegionType.MIXED, area: 19800, riskScore: 0.1, coordinates: [44.66, 16.14] },
  { id: '5', name: 'Prenj Mountain', type: RegionType.LOW_VEGETATION, area: 12000, riskScore: 0.6, coordinates: [43.53, 17.91] },
  { id: '6', name: 'Bjelašnica Range', type: RegionType.CONIFEROUS, area: 9500, riskScore: 0.75, coordinates: [43.70, 18.25] },
  { id: '7', name: 'Jahorina Forest', type: RegionType.CONIFEROUS, area: 8200, riskScore: 0.65, coordinates: [43.73, 18.56] },
  { id: '8', name: 'Vlašić Plateau', type: RegionType.MIXED, area: 11000, riskScore: 0.5, coordinates: [44.29, 17.65] },
  { id: '9', name: 'Trebević Park', type: RegionType.CONIFEROUS, area: 2100, riskScore: 0.9, coordinates: [43.82, 18.45] },
  { id: '10', name: 'Maglić Massif', type: RegionType.MIXED, area: 6000, riskScore: 0.3, coordinates: [43.28, 18.73] },
  { id: '11', name: 'Čvrsnica Reserve', type: RegionType.MAQUIS, area: 14500, riskScore: 0.7, coordinates: [43.60, 17.61] },
  { id: '12', name: 'Vranica Central', type: RegionType.LOW_VEGETATION, area: 7800, riskScore: 0.4, coordinates: [43.96, 17.71] },
  { id: '13', name: 'Zelengora Slopes', type: RegionType.CONIFEROUS, area: 13200, riskScore: 0.25, coordinates: [43.36, 18.57] },
  { id: '14', name: 'Majevica Hills', type: RegionType.DECIDUOUS, area: 9000, riskScore: 0.55, coordinates: [44.53, 18.82] },
  { id: '15', name: 'Ozren Mountain', type: RegionType.MIXED, area: 5500, riskScore: 0.6, coordinates: [44.59, 18.31] },
  { id: '16', name: 'Grmeč Forest', type: RegionType.CONIFEROUS, area: 15000, riskScore: 0.35, coordinates: [44.66, 16.42] },
  { id: '17', name: 'Klekovača Reserve', type: RegionType.CONIFEROUS, area: 8800, riskScore: 0.2, coordinates: [44.43, 16.51] },
  { id: '18', name: 'Manjača Highlands', type: RegionType.LOW_VEGETATION, area: 4200, riskScore: 0.45, coordinates: [44.60, 17.05] },
  { id: '19', name: 'Motajica Forest', type: RegionType.DECIDUOUS, area: 3100, riskScore: 0.5, coordinates: [45.05, 17.66] },
  { id: '20', name: 'Romanija Plateau', type: RegionType.CONIFEROUS, area: 10500, riskScore: 0.85, coordinates: [43.88, 18.66] },
  { id: '21', name: 'Velež Range', type: RegionType.MAQUIS, area: 6700, riskScore: 0.78, coordinates: [43.31, 17.91] },
  { id: '22', name: 'Šator Mountain', type: RegionType.MIXED, area: 5900, riskScore: 0.4, coordinates: [44.16, 16.60] },
  { id: '23', name: 'Dinara Border', type: RegionType.LOW_VEGETATION, area: 12800, riskScore: 0.62, coordinates: [44.05, 16.43] },
  { id: '24', name: 'Hutovo Blato', type: RegionType.MAQUIS, area: 7411, riskScore: 0.8, coordinates: [43.05, 17.78] }
];

export const REGION_STYLES: Record<RegionType, { color: string; iconType: string; label?: string }> = {
  [RegionType.DECIDUOUS]: { color: '#4ade80', iconType: 'tree', label: 'Deciduous' },
  [RegionType.CONIFEROUS]: { color: '#14532d', iconType: 'pine', label: 'Coniferous' },
  [RegionType.MIXED]: { color: '#a855f7', iconType: 'mixed', label: 'Mixed Forest' },
  [RegionType.MAQUIS]: { color: '#eab308', iconType: 'shrub', label: 'Maquis' },
  [RegionType.LOW_VEGETATION]: { color: '#ec4899', iconType: 'sprout', label: 'Low Veg' },
  [RegionType.LANDFILL]: { color: '#ef4444', iconType: 'trash', label: 'Landfill' },
};

export const PROTECTED_AREAS_DATA = [
  { name: 'Sutjeska National Park', type: 'National Park', lat: 43.3333, lng: 18.6833, areaSqKm: 175, intensity: 1.0 },
  { name: 'Una National Park', type: 'National Park', lat: 44.4939, lng: 16.1214, areaSqKm: 198, intensity: 0.95 },
  { name: 'Kozara National Park', type: 'National Park', lat: 45.0114, lng: 16.9039, areaSqKm: 34, intensity: 0.9 },
  { name: 'Drina National Park', type: 'National Park', lat: 43.9536, lng: 19.2944, areaSqKm: 63, intensity: 0.9 },
  { name: 'Blidinje Nature Park', type: 'Nature Park', lat: 43.6108, lng: 17.5133, areaSqKm: 358, intensity: 0.85 },
  { name: 'Hutovo Blato', type: 'Nature Park', lat: 43.0542, lng: 17.7847, areaSqKm: 74, intensity: 0.85 },
  { name: 'Vrelo Bosne', type: 'Nature Monument', lat: 43.8188, lng: 18.2694, areaSqKm: 6, intensity: 0.8 },
  { name: 'Skakavac', type: 'Nature Monument', lat: 43.9458, lng: 18.4489, areaSqKm: 14, intensity: 0.75 },
  { name: 'Tajan', type: 'Nature Park', lat: 44.3031, lng: 18.1822, areaSqKm: 50, intensity: 0.75 },
  { name: 'Bijambare', type: 'Protected Landscape', lat: 44.0875, lng: 18.5122, areaSqKm: 5, intensity: 0.75 },
  { name: 'Trebević', type: 'Protected Landscape', lat: 43.8372, lng: 18.4486, areaSqKm: 20, intensity: 0.8 },
  { name: 'Konjuh', type: 'Protected Landscape', lat: 44.3161, lng: 18.6092, areaSqKm: 80, intensity: 0.7 },
  { name: 'Bentbaša', type: 'Protected Landscape', lat: 43.8611, lng: 18.4431, areaSqKm: 2, intensity: 0.65 },
  { name: 'Prokoško Jezero', type: 'Nature Monument', lat: 43.9575, lng: 17.7533, areaSqKm: 10, intensity: 0.7 },
  { name: 'Livanjsko Polje', type: 'Ramsar Site', lat: 43.8347, lng: 16.8336, areaSqKm: 458, intensity: 0.8 },
  { name: 'Bardača', type: 'Ramsar Site', lat: 45.1014, lng: 17.4431, areaSqKm: 35, intensity: 0.8 },
];
