
import { ForestRegion, IncidentType, Language, IncidentReport } from './types';

export const BIH_CENTER: [number, number] = [44.3333, 17.8333];

export const BIH_GEOJSON: any = {
  type: "Feature",
  properties: { name: "Bosnia and Herzegovina" },
  geometry: {
    type: "Polygon",
    coordinates: [[
      [16.11, 45.19], [16.25, 45.22], [16.48, 45.15], [16.63, 45.23], [16.89, 45.25], 
      [17.15, 45.18], [17.38, 45.12], [17.51, 45.14], [17.75, 45.11], [18.15, 45.10], 
      [18.35, 45.02], [18.52, 44.93], [18.78, 44.89], [19.01, 44.86], [19.18, 44.85], 
      [19.38, 44.75], [19.55, 44.62], [19.62, 44.39], [19.45, 44.22], [19.27, 44.02], 
      [19.35, 43.85], [19.58, 43.68], [19.42, 43.55], [19.12, 43.35], [18.95, 43.32], 
      [18.73, 43.27], [18.58, 43.05], [18.42, 42.61], [18.25, 42.63], [18.15, 42.67], 
      [17.95, 42.75], [17.81, 42.92], [17.53, 42.94], [17.56, 43.14], [17.35, 43.28], 
      [17.18, 43.46], [16.95, 43.65], [16.75, 43.85], [16.51, 44.05], [16.25, 44.10], 
      [15.95, 44.08], [15.75, 44.13], [15.85, 44.45], [15.82, 44.78], [15.95, 44.95], 
      [16.11, 45.19]
    ]]
  }
};

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: "NFSSI",
    tagline: "Forest Surveillance & Early Alert",
    map: "Map",
    filters: "Filters",
    layers: "Layers",
    reports: "Reports",
    stats: "Analytics",
    reportIncident: "Report Incident",
    fireAlert: "Fire Alert",
    floodAlert: "Flood Alert",
    description: "Description",
    location: "Location",
    submit: "Submit Alert",
    cancel: "Cancel",
    low: "Low",
    medium: "Medium",
    high: "High",
    urgency: "Urgency",
    riskLevel: "Risk Level",
    forestDensity: "Forest Density",
    satellite: "Satellite",
    terrain: "Terrain",
    activeIncidents: "Active Incidents",
    bihSurveillance: "BiH National Surveillance",
    recentReports: "Recent Community Reports",
    locateMe: "Locate Me",
    borders: "Borders",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    on: "ON",
    off: "OFF",
    gisLegend: "GIS Legend",
    verifiedData: "Verified Data",
    totalProtected: "Total Protected Area",
    activeHotspots: "Active Fire Hotspots",
    avgRiskIndex: "Avg Risk Index",
    histComparison: "Historical Risk Comparison",
    forestType: "Forest Type",
    regFilters: "Regional Filters",
    riskThreshold: "Risk Threshold",
    allTypes: "All Types",
    critical: "CRITICAL",
    nasaFirms: "NASA FIRMS (Satellite)",
    weather: "Weather & Wind",
    windSpeed: "Wind Speed",
    temperature: "Temperature",
    riverLevel: "River Level",
    floodAlarm: "Flood Alarm",
    forests: {
      "Sutjeska National Park": "Sutjeska National Park",
      "Bjelašnica Range": "Bjelašnica Range",
      "Coniferous": "Coniferous",
      "Deciduous": "Deciduous",
      "Mixed": "Mixed",
      "Old-growth": "Old-growth",
      "Rocky Forest": "Rocky Forest"
    }
  },
  [Language.BS]: {
    appName: "NFSSI",
    tagline: "Nadzor šuma i rano upozoravanje",
    map: "Mapa",
    filters: "Filteri",
    layers: "Slojevi",
    reports: "Prijave",
    stats: "Analitika",
    reportIncident: "Prijavi incident",
    fireAlert: "Požar",
    floodAlert: "Poplava",
    description: "Opis",
    location: "Lokacija",
    submit: "Pošalji prijavu",
    cancel: "Odustani",
    low: "Nizak",
    medium: "Srednji",
    high: "Visok",
    urgency: "Hitnost",
    riskLevel: "Nivo rizika",
    forestDensity: "Gustoća šume",
    satellite: "Satelit",
    terrain: "Teren",
    activeIncidents: "Aktivni incidenti",
    bihSurveillance: "BiH Nacionalni Nadzor",
    recentReports: "Nedavne prijave zajednice",
    locateMe: "Lociraj me",
    borders: "Granice",
    theme: "Tema",
    light: "Svijetla",
    dark: "Tamna",
    on: "UKLJ",
    off: "ISKLJ",
    gisLegend: "GIS Legenda",
    verifiedData: "Provjereni podaci",
    totalProtected: "Ukupna zaštićena površina",
    activeHotspots: "Aktivni požari",
    avgRiskIndex: "Prosječni rizik",
    histComparison: "Historijsko poređenje",
    forestType: "Tip šume",
    regFilters: "Regionalni filteri",
    riskThreshold: "Prag rizika",
    allTypes: "Svi tipovi",
    critical: "KRITIČNO",
    nasaFirms: "NASA FIRMS (Satelit)",
    weather: "Meteo & Vjetar",
    windSpeed: "Brzina vjetra",
    temperature: "Temperatura",
    riverLevel: "Vodostaj",
    floodAlarm: "Alarm poplave",
    forests: {
      "Sutjeska National Park": "NP Sutjeska",
      "Bjelašnica Range": "Masiv Bjelašnica",
      "Coniferous": "Četinari",
      "Deciduous": "Listopadna",
      "Mixed": "Mješovita",
      "Old-growth": "Prašuma",
      "Rocky Forest": "Krševita šuma"
    }
  },
  [Language.JA]: {
    appName: "NFSSI",
    tagline: "森林監視・早期警戒システム",
    map: "マップ",
    filters: "フィルター",
    layers: "レイヤー",
    reports: "報告一覧",
    stats: "データ分析",
    reportIncident: "被害を報告する",
    fireAlert: "火災アラート",
    floodAlert: "洪水アラート",
    description: "詳細",
    location: "位置情報",
    submit: "アラート送信",
    cancel: "キャンセル",
    low: "低",
    medium: "中",
    high: "高",
    urgency: "緊急度",
    riskLevel: "リスクレベル",
    forestDensity: "森林密度",
    satellite: "衛星写真",
    terrain: "地形図",
    activeIncidents: "現在のアラート",
    bihSurveillance: "ボスニア・ヘルツェゴビナ監視",
    recentReports: "最近のコミュニティ報告",
    locateMe: "現在地を表示",
    borders: "国境",
    theme: "テーマ",
    light: "ライト",
    dark: "ダーク",
    on: "オン",
    off: "オフ",
    gisLegend: "GIS 凡例",
    verifiedData: "確認済みデータ",
    totalProtected: "総保護面積",
    activeHotspots: "火災発生数",
    avgRiskIndex: "平均リスク指数",
    histComparison: "過去のリスク比較",
    forestType: "森林タイプ",
    regFilters: "地域フィルター",
    riskThreshold: "リスクしきい値",
    allTypes: "すべてのタイプ",
    critical: "致命的",
    nasaFirms: "NASA FIRMS (衛星)",
    weather: "気象・風速",
    windSpeed: "風速",
    temperature: "気温",
    riverLevel: "水位",
    floodAlarm: "洪水警報",
    forests: {
      "Sutjeska National Park": "ストイェスカ国立公園",
      "Bjelašnica Range": "ビイェラシュニツァ山脈",
      "Coniferous": "針葉樹林",
      "Deciduous": "広葉樹林",
      "Mixed": "混合林",
      "Old-growth": "原生林",
      "Rocky Forest": "岩石森林"
    }
  }
};

export const MOCK_FORESTS: ForestRegion[] = [
  { id: '1', name: 'Sutjeska National Park', type: 'Old-growth', area: 17500, riskScore: 0.2, coordinates: [43.3444, 18.6833] },
  { id: '2', name: 'Kozara National Park', type: 'Deciduous', area: 3375, riskScore: 0.45, coordinates: [45.0083, 16.8914] },
  { id: '3', name: 'Mount Igman', type: 'Coniferous', area: 5400, riskScore: 0.8, coordinates: [43.75, 18.25] },
  { id: '4', name: 'Una National Park', type: 'Mixed', area: 19800, riskScore: 0.1, coordinates: [44.66, 16.14] },
  { id: '5', name: 'Prenj Mountain', type: 'Rocky Forest', area: 12000, riskScore: 0.6, coordinates: [43.53, 17.91] },
  { id: '6', name: 'Bjelašnica Range', type: 'Coniferous', area: 9500, riskScore: 0.75, coordinates: [43.70, 18.25] },
  { id: '7', name: 'Jahorina Forest', type: 'Mixed', area: 8200, riskScore: 0.65, coordinates: [43.73, 18.56] },
  { id: '8', name: 'Vlašić Plateau', type: 'Deciduous', area: 11000, riskScore: 0.5, coordinates: [44.29, 17.65] },
  { id: '9', name: 'Trebević Park', type: 'Mixed', area: 2100, riskScore: 0.9, coordinates: [43.82, 18.45] },
  { id: '10', name: 'Maglić Massif', type: 'Old-growth', area: 6000, riskScore: 0.3, coordinates: [43.28, 18.73] },
  { id: '11', name: 'Čvrsnica Reserve', type: 'Rocky Forest', area: 14500, riskScore: 0.7, coordinates: [43.60, 17.61] },
  { id: '12', name: 'Vranica Central', type: 'Mixed', area: 7800, riskScore: 0.4, coordinates: [43.96, 17.71] },
  { id: '13', name: 'Zelengora Slopes', type: 'Coniferous', area: 13200, riskScore: 0.25, coordinates: [43.36, 18.57] },
  { id: '14', name: 'Majevica Hills', type: 'Deciduous', area: 9000, riskScore: 0.55, coordinates: [44.53, 18.82] },
  { id: '15', name: 'Ozren Mountain', type: 'Mixed', area: 5500, riskScore: 0.6, coordinates: [44.59, 18.31] },
  { id: '16', name: 'Grmeč Forest', type: 'Coniferous', area: 15000, riskScore: 0.35, coordinates: [44.66, 16.42] },
  { id: '17', name: 'Klekovača Reserve', type: 'Old-growth', area: 8800, riskScore: 0.2, coordinates: [44.43, 16.51] },
  { id: '18', name: 'Manjača Highlands', type: 'Deciduous', area: 4200, riskScore: 0.45, coordinates: [44.60, 17.05] },
  { id: '19', name: 'Motajica Forest', type: 'Mixed', area: 3100, riskScore: 0.5, coordinates: [45.05, 17.66] },
  { id: '20', name: 'Romanija Plateau', type: 'Coniferous', area: 10500, riskScore: 0.85, coordinates: [43.88, 18.66] },
  { id: '21', name: 'Velež Range', type: 'Rocky Forest', area: 6700, riskScore: 0.78, coordinates: [43.31, 17.91] },
  { id: '22', name: 'Šator Mountain', type: 'Mixed', area: 5900, riskScore: 0.4, coordinates: [44.16, 16.60] },
  { id: '23', name: 'Dinara Border', type: 'Coniferous', area: 12800, riskScore: 0.62, coordinates: [44.05, 16.43] }
];

// Fix: Import IncidentReport from types.ts to fix the 'Cannot find name' error.
export const INITIAL_INCIDENTS: IncidentReport[] = [
  { id: 'i1', type: IncidentType.FIRE, lat: 43.8, lng: 18.3, description: 'Small brush fire near residential area', timestamp: Date.now() - 3600000, urgency: 'high', windDirection: 220, windSpeed: 15 },
  { id: 'i2', type: IncidentType.FLOOD, lat: 44.8, lng: 17.2, description: 'River bank overflow detected', timestamp: Date.now() - 7200000, urgency: 'medium' }
];
